services:
  - type: web
    name: structure-segmentation-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: API_KEY
        sync: false
    plan: free
